dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.4.1
  - smartcontractkit/chainlink-brownie-contracts@0.3.0
  - Brechtpd/base64@1.1.0
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.4.1'
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.3.0'
      - 'base64-sol=Brechtpd/base64@1.1.0' 
networks:
  mumbai_moralis:
    vrf_coordinator: '0x8C7382F9D8f56b33781fE506E897a4F1e2d17255'
    link_token: '0x326C977E6efc84E512bB9C30f76E30c160eD06FB'
    keyhash: '0x6e75b569a01ef56d18cab6a8e71e6600d6ce853834d4a5748b720d06f878b3a4'
    fee: 1000000000000000
wallets:
  from_key: ${PRIVATE_KEY}
  from_mnemonic: ${MNEMONIC}
